version: "3.9"
services:
    app:
        context: .
        dockerfile: Dockerfile
    db:
        image: "postgres:latest"
        restart: always
        environment:
            POSTGRESS_PWD: password
            POSTGRES_DB: iot-practice
        ports:
            - 5432:5432
        volumes:
            - "db_volume:/var/lib/postgresql/data"
volumes:
    db_volume:
